# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-06 14:39
from __future__ import unicode_literals

from django.db import migrations, models
import uploader.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expense_date', uploader.models.WvDateField()),
                ('category', models.CharField(max_length=64)),
                ('employee_name', models.CharField(max_length=128)),
                ('employee_address', models.TextField()),
                ('expense_description', models.CharField(max_length=256)),
                ('pretax_amount', models.DecimalField(decimal_places=2, max_digits=7)),
                ('tax_name', models.CharField(max_length=64)),
                ('tax_amount', models.DecimalField(decimal_places=2, max_digits=7)),
            ],
        ),
    ]
