# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-07 02:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploader', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='expense_date',
            field=models.CharField(max_length=64),
        ),
    ]
