# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-07 02:29
from __future__ import unicode_literals

from django.db import migrations
import uploader.models


class Migration(migrations.Migration):

    dependencies = [
        ('uploader', '0002_auto_20161107_0220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='expense_date',
            field=uploader.models.WvDateField(),
        ),
    ]
