# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-20 22:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense_reports', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='pretax_amount',
            field=models.DecimalField(decimal_places=2, max_digits=7, null=True),
        ),
    ]
