# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-20 22:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense_reports', '0002_expense_pretax_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='employee_name',
            field=models.CharField(max_length=35, null=True),
        ),
    ]
