# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-21 02:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense_reports', '0004_expense_tax_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='employee_address',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
