# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-21 02:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense_reports', '0005_expense_employee_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='category',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
