# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-21 02:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense_reports', '0006_expense_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
