# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-21 02:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense_reports', '0007_expense_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='tax_name',
            field=models.CharField(default='', max_length=35),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='expense',
            name='employee_address',
            field=models.CharField(default='', max_length=150),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='expense',
            name='employee_name',
            field=models.CharField(default='', max_length=35),
            preserve_default=False,
        ),
    ]
