# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-21 02:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense_reports', '0008_auto_20161121_0242'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='expense_description',
            field=models.CharField(default='', max_length=150),
            preserve_default=False,
        ),
    ]
