# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-21 15:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense_reports', '0010_expensereport'),
    ]

    operations = [
        migrations.AddField(
            model_name='expensereport',
            name='report',
            field=models.FileField(null=True, upload_to='expense_reports'),
        ),
    ]
