# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-21 15:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('expense_reports', '0011_expensereport_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='expense_report',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='expense_reports.ExpenseReport'),
        ),
        migrations.AlterField(
            model_name='expensereport',
            name='report',
            field=models.FileField(null=True, upload_to='expense_reports/'),
        ),
    ]
