# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-02 01:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Expenses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('category', models.CharField(max_length=100)),
                ('employee_name', models.CharField(max_length=200)),
                ('employee_address', models.CharField(max_length=500)),
                ('description', models.CharField(max_length=500)),
                ('pt_amount', models.FloatField()),
                ('tax_name', models.CharField(max_length=100)),
                ('amount', models.FloatField()),
            ],
        ),
    ]
