# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-05 22:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uploader', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expenses',
            old_name='amount',
            new_name='tax_amount',
        ),
    ]
