//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wave.Employee.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Expense
    {
        public int ExpenseId { get; set; }
        public int ExpenseCategoryId { get; set; }
        public int EmployeeId { get; set; }
        public string ExpenseDescription { get; set; }
        public decimal PreTaxAmount { get; set; }
        public int TaxStateId { get; set; }
        public decimal TaxAmount { get; set; }
        public System.DateTime SubmissionDate { get; set; }
        public System.Guid rowguid { get; set; }
        public virtual Employee Employee { get; set; }
        public virtual ExpenseCategory ExpenseCategory { get; set; }
        public virtual TaxState TaxState { get; set; }

    }
}
