# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-08 15:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='date')),
                ('category', models.CharField(default='', max_length=100, verbose_name='category')),
                ('employee_name', models.CharField(max_length=100, verbose_name='employ name')),
                ('employee_address', models.TextField(default='', verbose_name='address')),
                ('expense_description', models.TextField(default='', verbose_name='expense notes')),
                ('pre_tax_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='pre-tax amount')),
                ('tax_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='tax amount')),
                ('tax_name', models.CharField(max_length=100, verbose_name='tax name')),
            ],
        ),
    ]
