# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-08 18:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='file_tag',
            field=models.CharField(default='', max_length=100, verbose_name='file_tag'),
        ),
    ]
