<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Query;

/**
 * ExpenseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ExpenseRepository extends EntityRepository
{
	/**
	 * 
	 * @return \Doctrine\ORM\QueryBuilder
	 */
	public function getByMonthDateQuery()
	{
		return $this->createQueryBuilder('e')
		->select('SUM(e.preTaxAmount) as preTaxSum')
		->addSelect('SUM(e.taxAmount) as taxSum')
		->addSelect('YEAR(e.expenseDate) AS expenseYear')
		->addSelect('MONTH(e.expenseDate) AS expenseMonth')
		->distinct()
		->groupBy('expenseYear')
		->addGroupBy('expenseMonth')
		->orderBy('expenseYear', 'ASC')
		->addOrderBy('expenseMonth', 'ASC')
		->getQuery()
		->setHydrationMode(Query::HYDRATE_ARRAY)
		;
	}
}
