# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-27 02:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('address', models.CharField(max_length=128)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('description', models.CharField(max_length=128)),
                ('pre_tax_amount', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Pre-Tax Amount')),
                ('tax_name', models.CharField(max_length=32)),
                ('tax_amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='csv_parser.Employee')),
            ],
            options={
                'ordering': ['date'],
            },
        ),
    ]
