# Generated by Django 2.0.2 on 2018-02-15 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Expenses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('category', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=200)),
                ('pretax', models.BigIntegerField()),
                ('taxname', models.CharField(max_length=100)),
                ('tax', models.BigIntegerField()),
            ],
        ),
    ]
