# Generated by Django 2.0.2 on 2018-02-26 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0003_expenses_filename'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenses',
            name='category',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='expenses',
            name='filename',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='expenses',
            name='taxname',
            field=models.CharField(max_length=50),
        ),
    ]
