old_sound_rabbit_mq:
    connections:
        default:
            host:     "%amqp_host%"
            port:     "%amqp_port%"
            user:     "%amqp_user%"
            password: "%amqp_pass%"
            vhost:    "%amqp_vhost%"
            lazy:     true
            connection_timeout: 600
            read_write_timeout: 1200 

            # requires php-amqplib v2.4.1+ and PHP5.4+
            keepalive: true

            # requires php-amqplib v2.4.1+
            heartbeat: 600

    producers:
#        upload_picture:
#            connection:       default
#            exchange_options: {name: 'upload-picture', type: direct}
#            service_alias:    my_app_service # no alias by default

        upload_expensefile:
            connection: default
            exchange_options: 
                name: 'amq.direct'
                type: direct
            queue_options:
                name: 'expense-datafiles'
                durable: true
            service_alias: 'expense.datafile.producer'
                            
    consumers:
#        upload_picture:
#            connection:       default
#            exchange_options: {name: 'upload-picture', type: direct}
#            queue_options:    {name: 'upload-picture'}
#            callback:         upload_picture_service
        expensefile:
            connection: default
            idle_timeout: 0
            qos_options:
                prefetch_size: 0
                prefetch_count: 1
                global: false
            exchange_options: 
                name: 'amq.direct'
                type: 'direct'
            queue_options:
                name: 'expense-datafiles'
            callback: 'expense.datafile.consumer'

            