# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-03 23:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('waveCSVChallenge', '0002_auto_20161001_1716'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taxinformation',
            name='tax_rate',
        ),
    ]
