"""Generate DB

Revision ID: b43d47a50fa9
Revises:
Create Date: 2016-09-01 09:09:54.784496

"""

# revision identifiers, used by Alembic.
revision = 'b43d47a50fa9'
down_revision = None
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('csv_files',
    sa.Column('csv_file_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('csv_file_id', name=op.f('pk_csv_files'))
    )
    op.create_table('expenses',
    sa.Column('expense_id', sa.Integer(), nullable=False),
    sa.Column('csv_file_id', sa.Integer(), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('category', sa.Text(), nullable=True),
    sa.Column('employee_name', sa.Text(), nullable=True),
    sa.Column('employee_address', sa.Text(), nullable=True),
    sa.Column('expense_description', sa.Text(), nullable=True),
    sa.Column('pre_tax_amount', sa.Numeric(), nullable=True),
    sa.Column('tax_name', sa.Text(), nullable=True),
    sa.Column('tax_amount', sa.Numeric(), nullable=True),
    sa.ForeignKeyConstraint(['csv_file_id'], [u'csv_files.csv_file_id'], name=op.f('fk_expenses_csv_file_id_csv_files')),
    sa.PrimaryKeyConstraint('expense_id', name=op.f('pk_expenses'))
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('expenses')
    op.drop_table('csv_files')
    ### end Alembic commands ###
