source 'https://rubygems.org'

ruby '2.1.0'

gem 'rails', '4.1.0'
gem 'sqlite3'
gem 'sass-rails', '~> 4.0.3'
gem 'uglifier', '>= 1.3.0'
gem 'jquery-rails'
gem 'jbuilder', '~> 2.0'

gem 'carrierwave'
gem 'quiet_assets'
gem 'sorcery'

group :development, :test do
  gem 'rspec-rails', '~> 2.0'
end

gem 'sdoc', '~> 0.4.0', group: :doc
gem 'spring', group: :development
