# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-28 19:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('addr', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Expenses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('category', models.CharField(max_length=128)),
                ('desc', models.CharField(max_length=255)),
                ('pre_tax_amt', models.DecimalField(decimal_places=2, max_digits=16)),
                ('tax_type', models.CharField(max_length=255)),
                ('tax_amt', models.DecimalField(decimal_places=2, max_digits=16)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expenses.Employee')),
            ],
        ),
    ]
