# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-29 01:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0003_auto_20151229_0143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenses',
            name='desc',
            field=models.CharField(max_length=255),
        ),
    ]
