# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-16 03:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('docfile', models.FileField(upload_to=b'documents/%Y-%m-%d')),
                ('created_time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('category', models.CharField(max_length=100)),
                ('employee_name', models.CharField(max_length=100)),
                ('employee_address', models.CharField(max_length=512)),
                ('expense_desc', models.CharField(max_length=100)),
                ('pretax_amt', models.DecimalField(decimal_places=2, max_digits=6)),
                ('tax_name', models.CharField(max_length=100)),
                ('tax_amount', models.DecimalField(decimal_places=2, max_digits=6)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Document')),
            ],
        ),
    ]
