# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-16 01:52
from __future__ import unicode_literals

import consume.models
from django.db import migrations, models
import django.db.models.deletion
import encrypted_fields.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='CSVFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload_date', models.DateField()),
                ('filename', models.CharField(max_length=100)),
                ('csv_file', models.FileField(upload_to='csv_backups')),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('description', encrypted_fields.fields.EncryptedCharField(max_length=250)),
                ('pre_tax_amount', consume.models.EncryptedDecimalField(decimal_places=2, default=0.0, max_digits=11, verbose_name='Pre-tax Amount')),
                ('tax_amount', consume.models.EncryptedDecimalField(decimal_places=2, default=0.0, max_digits=11)),
                ('deleted', models.BooleanField(default=False)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consume.Category')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consume.Employee')),
                ('source_file', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='consume.CSVFile')),
            ],
        ),
        migrations.CreateModel(
            name='Tax',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
            ],
            options={
                'verbose_name': 'Tax',
                'verbose_name_plural': 'Taxes',
            },
        ),
        migrations.AddField(
            model_name='expense',
            name='tax',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consume.Tax'),
        ),
    ]
