# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6b978e808a5183c2746f601cdf44e2e05551a9a30bfd77a180f1fd6edfca9d499e9f4a8db11f49f98e64efe95bd3c04438f83b1880996785e8353717c46033eb

test:
  secret_key_base: 4dc3e2ae9b8eb4e22275d7d2fa265ae89ba1c3840a5040eff1d3c193f1a00da89368de512cdf3174e6cd7b0a26b9302624546b34ded2098f950512b3dde2eb2d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
