# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: da91ae1c6a9056766e37a42c41c9d95ebadcdfb55867fb3780a82b85a85ab94c8194df29d306a1a94bf1cad95dd0b31a36b34e297182904c1261099e4737bcf9

test:
  secret_key_base: c9e41fbbf61a87b3f8566f25049125b6337aab07103fbd347db458690e8af3ae2f7e6642c3e00103a13f560644638e3da9a024db465b67fd40c804acfa8e0eeb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
