services:
#    app.example:
#        class: AppBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]

    expense.datafile.consumer:
        class: AppBundle\Consumer\ExpenseDatafileConsumer
        calls:
            - [ setLogger, ["@logger"]]
            - [ setRedis, ["@snc_redis.default"]]
            - [ setEntityManager, ["@doctrine.orm.entity_manager"]]
