# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-18 02:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company_Database',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateTimeField(verbose_name='')),
                ('Category', models.CharField(max_length=200)),
                ('EmployeeName', models.CharField(max_length=200)),
                ('EmployeeAddress', models.CharField(max_length=200)),
                ('Expense', models.DecimalField(decimal_places=2, max_digits=19)),
                ('ExpenseDesc', models.TextField()),
                ('PreTaxAmt', models.DecimalField(decimal_places=2, max_digits=19)),
                ('TaxName', models.CharField(max_length=200)),
                ('TaxAmt', models.DecimalField(decimal_places=2, max_digits=19)),
            ],
        ),
    ]
