# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-01 22:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='CSVSource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=50)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expense.CSVSource')),
            ],
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('description', models.CharField(max_length=50)),
                ('preTaxAmount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('taxAmount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expense.Category')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expense.Employee')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expense.CSVSource')),
            ],
        ),
        migrations.CreateModel(
            name='Tax',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=50)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expense.CSVSource')),
            ],
        ),
        migrations.AddField(
            model_name='expense',
            name='tax',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expense.Tax'),
        ),
        migrations.AddField(
            model_name='category',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expense.CSVSource'),
        ),
    ]
