# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-09 20:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0002_job_jobparameters'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='JobParameters',
            new_name='JobParameter',
        ),
        migrations.AddField(
            model_name='expense',
            name='job',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='expense.Job'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='source',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='expense.CSVSource'),
        ),
        migrations.AlterField(
            model_name='job',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
