# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-12 20:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0003_auto_20160909_1653'),
    ]

    operations = [
        migrations.AddField(
            model_name='csvsource',
            name='defaultLocale',
            field=models.CharField(default='english-us', max_length=50),
        ),
    ]
