# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-24 01:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0003_auto_20161123_2004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monthlyexpenditure',
            name='year',
            field=models.IntegerField(default=2013),
        ),
    ]
