# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-24 01:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0004_auto_20161123_2006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monthlyexpenditure',
            name='year',
            field=models.IntegerField(),
        ),
    ]
