<!DOCTYPE html>
<html>
<head>
	<title>{% block title %}{% endblock %}</title>
	<link href="//netdna.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap.min.css" rel="stylesheet">
	<link href="/static/thirdparty/bootstrap-fileinput-master/css/fileinput.min.css" media="all" rel="stylesheet" type="text/css" />
	<script src="//ajax.googleapis.com/ajax/libs/jquery/2.0.0/jquery.min.js"></script>
	<script src="/static/thirdparty/bootstrap-fileinput-master/js/fileinput.min.js"></script>
</head>

<body>
<div class="container">
{% block content %}{% endblock %}
</div>
</body>
{% block javascript %}{% endblock %}
</html>