# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-20 20:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Expenses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='date expensed')),
                ('employee_name', models.CharField(max_length=100)),
                ('employee_address', models.CharField(max_length=140)),
                ('category', models.CharField(max_length=64)),
                ('description', models.CharField(max_length=140)),
                ('pretax', models.FloatField(default=0)),
                ('tax_name', models.CharField(max_length=64)),
                ('tax', models.FloatField(default=0)),
            ],
        ),
    ]
