# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-17 20:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='First and last name are expected.', max_length=255, verbose_name='Full Name')),
                ('address', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('charged_on', models.DateField(help_text='The date on which the employee charged this expensive.')),
                ('description', models.CharField(help_text='A brief description of the expense.', max_length=511)),
                ('pretax_amount', models.DecimalField(decimal_places=2, help_text='The dollar amount BEFORE taxes.', max_digits=12)),
            ],
        ),
        migrations.CreateModel(
            name='ExpenseCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='A descriptive name to indicate the reason for an expense.', max_length=255, verbose_name='Category Name')),
                ('subcategory', models.CharField(blank=True, help_text='Allows for more specificity in the reason for an expense.', max_length=255, verbose_name='Subcategory Name')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='expensecategory',
            unique_together=set([('name', 'subcategory')]),
        ),
        migrations.AddField(
            model_name='expense',
            name='category',
            field=models.ForeignKey(help_text='The category this expense best belongs to.', on_delete=django.db.models.deletion.CASCADE, to='consumer.ExpenseCategory'),
        ),
        migrations.AddField(
            model_name='expense',
            name='employee',
            field=models.ForeignKey(help_text='The employee reporting this expense.', on_delete=django.db.models.deletion.CASCADE, to='consumer.Employee'),
        ),
    ]
