USE [master]
GO
/****** Object:  Database [Wave_X1_Main]    Script Date: 31-Oct-16 2:21:12 PM ******/
CREATE DATABASE [Wave_X1_Main]
GO
ALTER DATABASE [Wave_X1_Main] SET COMPATIBILITY_LEVEL = 120
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Wave_X1_Main].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [Wave_X1_Main] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [Wave_X1_Main] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [Wave_X1_Main] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [Wave_X1_Main] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [Wave_X1_Main] SET ARITHABORT OFF 
GO
ALTER DATABASE [Wave_X1_Main] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [Wave_X1_Main] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [Wave_X1_Main] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [Wave_X1_Main] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [Wave_X1_Main] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [Wave_X1_Main] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [Wave_X1_Main] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [Wave_X1_Main] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [Wave_X1_Main] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [Wave_X1_Main] SET  ENABLE_BROKER 
GO
ALTER DATABASE [Wave_X1_Main] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [Wave_X1_Main] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [Wave_X1_Main] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [Wave_X1_Main] SET ALLOW_SNAPSHOT_ISOLATION ON 
GO
ALTER DATABASE [Wave_X1_Main] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [Wave_X1_Main] SET READ_COMMITTED_SNAPSHOT ON 
GO
ALTER DATABASE [Wave_X1_Main] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [Wave_X1_Main] SET RECOVERY FULL 
GO
ALTER DATABASE [Wave_X1_Main] SET  MULTI_USER 
GO
ALTER DATABASE [Wave_X1_Main] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [Wave_X1_Main] SET DB_CHAINING OFF 
GO
ALTER DATABASE [Wave_X1_Main] SET QUERY_STORE = ON
GO
ALTER DATABASE [Wave_X1_Main] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 100, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO)
GO
USE [Wave_X1_Main]
GO
ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET MAXDOP = PRIMARY;
GO
ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET LEGACY_CARDINALITY_ESTIMATION = PRIMARY;
GO
ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET PARAMETER_SNIFFING = PRIMARY;
GO
ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET QUERY_OPTIMIZER_HOTFIXES = PRIMARY;
GO
USE [Wave_X1_Main]
GO
/****** Object:  Table [dbo].[Employee]    Script Date: 31-Oct-16 2:21:13 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Employee](
	[EmployeeId] [int] IDENTITY(1,1) NOT NULL,
	[FirstName] [varchar](50) NOT NULL,
	[LastName] [varchar](50) NOT NULL,
	[Address] [varchar](200) NOT NULL,
	[rowguid] [uniqueidentifier] ROWGUIDCOL  NOT NULL,
	[CreatedDate] [datetime] NOT NULL,
 CONSTRAINT [PK_Employee] PRIMARY KEY CLUSTERED 
(
	[EmployeeId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
)

GO
/****** Object:  Table [dbo].[Expense]    Script Date: 31-Oct-16 2:21:21 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Expense](
	[ExpenseId] [int] IDENTITY(1,1) NOT NULL,
	[ExpenseCategoryId] [int] NOT NULL,
	[EmployeeId] [int] NOT NULL,
	[ExpenseDescription] [varchar](200) NOT NULL,
	[PreTaxAmount] [decimal](18, 2) NOT NULL,
	[TaxStateId] [int] NOT NULL,
	[TaxAmount] [decimal](18, 2) NOT NULL,
	[SubmissionDate] [datetime] NOT NULL,
	[rowguid] [uniqueidentifier] ROWGUIDCOL  NOT NULL,
 CONSTRAINT [PK_Expense] PRIMARY KEY CLUSTERED 
(
	[ExpenseId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
)

GO
/****** Object:  Table [dbo].[ExpenseCategory]    Script Date: 31-Oct-16 2:21:32 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[ExpenseCategory](
	[CategoryId] [int] IDENTITY(1,1) NOT NULL,
	[CategoryName] [nchar](100) NOT NULL,
	[rowguid] [uniqueidentifier] NOT NULL,
 CONSTRAINT [PK_ExpenseCategory] PRIMARY KEY CLUSTERED 
(
	[CategoryId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
)

GO
/****** Object:  Table [dbo].[TaxState]    Script Date: 31-Oct-16 2:21:36 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[TaxState](
	[StateId] [int] IDENTITY(1,1) NOT NULL,
	[StateName] [varchar](50) NOT NULL,
	[StateCode] [varchar](2) NOT NULL,
	[rowguid] [uniqueidentifier] NOT NULL,
 CONSTRAINT [PK_TaxState] PRIMARY KEY CLUSTERED 
(
	[StateId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
)

GO
ALTER TABLE [dbo].[Employee] ADD  CONSTRAINT [DF_Employee_rowguid]  DEFAULT (newid()) FOR [rowguid]
GO
ALTER TABLE [dbo].[Employee] ADD  CONSTRAINT [DF_Employee_CreatedDate]  DEFAULT (getdate()) FOR [CreatedDate]
GO
ALTER TABLE [dbo].[Expense] ADD  CONSTRAINT [DF_Expense_SubmissionDate]  DEFAULT (getdate()) FOR [SubmissionDate]
GO
ALTER TABLE [dbo].[Expense] ADD  CONSTRAINT [DF_Expense_rowguid]  DEFAULT (newid()) FOR [rowguid]
GO
ALTER TABLE [dbo].[Expense]  WITH CHECK ADD  CONSTRAINT [FK_Expense_Category_CategoryId] FOREIGN KEY([ExpenseCategoryId])
REFERENCES [dbo].[ExpenseCategory] ([CategoryId])
GO
ALTER TABLE [dbo].[Expense] CHECK CONSTRAINT [FK_Expense_Category_CategoryId]
GO
ALTER TABLE [dbo].[Expense]  WITH CHECK ADD  CONSTRAINT [FK_Expense_Employee_EmployeeId] FOREIGN KEY([EmployeeId])
REFERENCES [dbo].[Employee] ([EmployeeId])
GO
ALTER TABLE [dbo].[Expense] CHECK CONSTRAINT [FK_Expense_Employee_EmployeeId]
GO
ALTER TABLE [dbo].[Expense]  WITH CHECK ADD  CONSTRAINT [FK_Expense_TaxState_StateId] FOREIGN KEY([TaxStateId])
REFERENCES [dbo].[TaxState] ([StateId])
GO
ALTER TABLE [dbo].[Expense] CHECK CONSTRAINT [FK_Expense_TaxState_StateId]
GO
USE [master]
GO
ALTER DATABASE [Wave_X1_Main] SET  READ_WRITE 
GO
