# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-05 23:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Employee',
        ),
        migrations.DeleteModel(
            name='Expenses',
        ),
    ]
