# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-06 16:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0003_employee_expenses'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expenses',
            name='employee',
        ),
        migrations.DeleteModel(
            name='Employee',
        ),
        migrations.DeleteModel(
            name='Expenses',
        ),
    ]
