# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-06 18:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0005_employees_expenses_uploadfile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expenses',
            name='employee',
        ),
        migrations.DeleteModel(
            name='UploadFile',
        ),
        migrations.DeleteModel(
            name='Employees',
        ),
        migrations.DeleteModel(
            name='Expenses',
        ),
    ]
