# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-08-03 04:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='Full name')),
            ],
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Date')),
                ('description', models.CharField(max_length=255, verbose_name='Description')),
                ('pre_tax', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Pre-tax amount')),
                ('tax_name', models.CharField(max_length=255, verbose_name='Tax type')),
                ('tax', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Tax amount')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='se_challenge.Category', verbose_name='Category')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='se_challenge.Employee', verbose_name='Employee')),
            ],
            options={
                'verbose_name': 'Entry',
                'verbose_name_plural': 'Entries',
            },
        ),
        migrations.CreateModel(
            name='OfficeAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=511, verbose_name='Address')),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_file', models.FileField(upload_to='', verbose_name='Report file')),
                ('upload_date', models.DateTimeField(auto_now_add=True, verbose_name='Upload date')),
            ],
        ),
        migrations.AddField(
            model_name='expense',
            name='employee_address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='se_challenge.OfficeAddress', verbose_name='Employee address'),
        ),
        migrations.AddField(
            model_name='expense',
            name='report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='se_challenge.Report', verbose_name='Report'),
        ),
        migrations.AddField(
            model_name='employee',
            name='addresses',
            field=models.ManyToManyField(to='se_challenge.OfficeAddress', verbose_name='Addresses'),
        ),
    ]
