# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d985398629103f27f836f08e74f27aaaa63930d6c368edab71f9b673c8b99ab45da8561b8a90ca9fa845a4aedf680263897f85d604e67e5939e6ca6a5274ed23

test:
  secret_key_base: 4351de8289d6e3fa1a3d3fca2b0341c1e79d9e1754bdc727dedd9c7d70cd56952da421815350f06ac22c026074ae1027df9abd4e2fd6dc3a292f4de1c964d83a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
